### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by melroy89** [mondalaci/kicad-components-to-json#1]
What is the reason to convert a component to a json string? :s

**Comment by mondalaci** [comment]
I use this module in https://github.com/mondalaci/kicad-bom-generator - Hopefully that answers your question. :)

**Comment by melroy89** [comment]
@mondalaci  Ah yes, it does. 
Currently when I try to generate a BOM, it need a plugin for some reason. It this a plugin what you are making. If so, why is it not part of the 'default' installation... I like to create spreadsheet or document using the DOM generator, but without any plugin (by default in KiCad) it doesn't do much...

**Comment by mondalaci** [comment]
@danger89 This is not a plugin but an external command line application. I'm not sure whether the KiCad folks would welcome my tools / libraries because these weren't written in Python, I'm not using their APIs and NPM is an additional dependency.

I also created a spreadsheet (CSV) out of the final JSON file which is a no brainer. Given that I'm working on a project that involves multiple boards I wanted an aggregated BOM which I was able to generate very easily with these libraries.

**Comment by melroy89** [comment]
Well the DOM plugin way-of-working is just executing a command. It can be Python, C++, or even bash..
Maybe it's not that hard to make a 'plugin' in KiCad after all? 

An example on Linux using another plugin:
http://og2k.com/content/how-generate-bill-materials-bom-kicad

**Comment by mondalaci** [comment]
Yeah, maybe it's easy to create a KiCad plugin but now that I'm already finished with these modules and they're working well I rather wouldn't put any more time into this.
